import type { Metadata } from "next";
import "./globals.css";
import { cn } from "./lib/utils";
import { Inter as FontSans } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartProvider } from './components/CartContext'; 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen bg-background font-sans antialiased", 
          fontSans.variable
        )}
      >
        <CartProvider>
        <Header />
        <main className="flex-grow"> 
          {children}
        </main>
          <Footer />
        </CartProvider>
      </body>
      </html>
      
  );
}